#!/bin/bash
#
# description: sssh server daemon

# Get function from functions library
. /etc/init.d/functions

start(){

    # needs to be root user
    if [[ $(id -u) -ne 0 ]] ; then echo "Please run as root" ; exit 1 ; fi

    sssh_server
}

stop(){
    sssh_server -mode=stop
}

reload(){
    echo "reload not implemented, try restart"
}

status(){
}


case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        reload)
                reload
		;;
        status)
                status
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart|reload|status}"
esac