#!/bin/sh

command_exists() {
	command -v "$@" >/dev/null 2>&1
}

mkdir /etc/sssh

sudo systemctl enable sssh_server

KEYFILE=/etc/sssh/rsa_host

if [ ! -f "$KEYFILE" ]; then
    /usr/local/bin/sssh_server -mode=keygen -filename=${KEYFILE}
fi

sudo systemctl start sssh_server

