#!/bin/sh
chmod -R 755 /usr/local/bin/sssh_server.script.sh
chmod -R 755 /Library/LaunchDaemons/com.ssshserver.app.plist

KEYFILE=/etc/sssh/rsa_host

mkdir -p /etc/sssh

if [ ! -f ${KEYFILE} ]; then
    /usr/local/bin/sssh_server -mode=keygen -filename=${KEYFILE} >> /tmp/com.ssshserver.app.out
fi

sudo launchctl load /Library/LaunchDaemons/com.ssshserver.app.plist
exit 0